kind: Service
apiVersion: v1
metadata:
  name: welcomeapp-service
spec:
  type: NodePort
  selector:
    app: welcomeapp
  ports:
  - protocol: TCP
    port: 8080
    LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcomeapp-deployment
  labels:
    app: welcomeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: welcomeapp
  template:
    metadata:
      labels:
        app: welcomeapp
    spec:
      containers:
      - name: welcomeapp
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
